#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
    ctags --tag-relative -L - -f "$$.tags" --languages=-javascript,sql \
    --fields=+aimlS --PHP-kinds=cdfint-av --exclude=*Test.php --exclude=*.json
mv "$$.tags" ".tags"
